# Caelestia-synced Starship prompt.

add_newline = false
palette = "caelestia"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nix_shell\
$cmd_duration\
$character"""

right_format = "$time"

[palettes.caelestia]
bg = "#2b2930"
user = "#5c87cf"
path = "#36b2ff"
git = "#7f75ff"
nix = "#c794ff"
time = "#343b4d"
exit = "#b7c6ee"
text = "#f2edf4"
accent_text = "#314060"
muted = "#aaa3ad"

[username]
show_always = true
style_user = "fg:user bold"
style_root = "fg:git bold"
format = "[$user]($style) "

[hostname]
ssh_only = true
style = "fg:user bold"
format = "[@$hostname]($style) "

[directory]
home_symbol = "~"
truncation_length = 3
truncation_symbol = ".../"
read_only = " ro"
style = "fg:path bold"
format = "[$path$read_only]($style) "

[git_branch]
symbol = ""
style = "fg:git bold"
format = "[$symbol $branch]($style) "

[git_status]
style = "fg:git bold"
format = "[$all_status$ahead_behind]($style) "
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = "s${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "x${count}"

[nix_shell]
symbol = "nix"
style = "fg:nix bold"
format = "[$symbol]($style) "

[cmd_duration]
min_time = 1000
style = "fg:muted bold"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](fg:exit bold)"
error_symbol = "[❯](fg:git bold)"
vimcmd_symbol = "[❮](fg:path bold)"

[time]
disabled = false
time_format = "%R"
style = "fg:time bold"
format = "[ $time]($style)"
